.github/workflows/ci.yml

and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

ci(ci): replace workflow-run-cleanup-action with github concurrency

---

.env.template
src/config/config.test.js
src/config/index.js
src/routes/pdf/txt/schema.js

BREAKING CHANGE: `OCR_ENABLED` environment variable now defaults to false.
Lower spec servers were struggling to run with the defaults, due to how CPU intensive Tesseract OCR workers are.

fix(config)!: `OCR_ENABLED` defaults to false

---

README.md

`.doc` files are notoriously difficult to parse due to them being based on the [Compound File Binary File Format](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/53989ce4-7b05-4f8d-829b-d08d6148375b), and tooling around it is sparse. The alternative is using LibreOffice or MS Office via the CLI, however that adds too much overhead.
closes #253
closes #254

docs(readme): remove planned features section

---

package-lock.json
package.json
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-txt/index.js

BREAKING CHANGE: minimum node engine bumped from `>=14.0.0` to `^14.17.0 || ^15.6.0 || >=16.0.0`

perf(plugins)!: replace `uuid` dep with `crypto.randomUUID()`

---

package-lock.json
package.json

Pinned fastify-swagger version to 3.12.0 as ^3.12.1 introduced this bug.
See https://github.com/fastify/fastify-swagger/issues/524

fix(routes/docs): resolve `token "definitions" does not exist` error

---

.eslintrc.js
.github/workflows/ci.yml
Dockerfile
README.md
package-lock.json
package.json

BREAKING CHANGE: minimum required version of node increased from 14.17.0 to 18.12.1
Node 14 and 16 becomes EOL in April and September 2023 respectively, which is the same time that [Yeovil District Hospital NHS Foundation Trust is due to merge with Somerset NHS Foundation Trust](https://yeovilhospital.co.uk/better-care-for-local-people-the-merger-of-yeovil-hospital-nhs-foundation-trust-with-somerset-nhs-foundation-trust/). Development will be focused on the merger at that point in time, so this PR preemptively drops support to reduce work load in the future.

chore!: drop support for node 14 and 16

---

.github/workflows/cd.yml

Should stop any malicious dev dependencies/scripts from being triggered in production if, when deploying, the user forgets the `--ignore-scripts --omit=dev` args.

ci(cd): remove dev values from `package.json`

---

src/plugins/tidy-css/plugin.test.js

See https://html.spec.whatwg.org/multipage/parsing.html#comment-end-bang-state
Closes #1275

test(plugins/tidy-css): html comments can end with exclamation marks

---

src/plugins/pdf-to-txt/index.js
src/routes/pdf/txt/schema.js

Barely worked and when it did it exposed underlying server details (the charsets).
Not a breaking change as it was broken to begin with!
https://github.com/Fdawgs/docsmith/pull/1353 will fill the space of listing supported encodings.

fix(routes/pdf/txt): remove `listEncodingOptions` qs param

---

src/plugins/pdf-to-html/index.js
src/routes/pdf/html/schema.js
src/routes/pdf/txt/schema.js

Charsets like 'utf-32' are not supported and throws errors, so limit charsets to only Poppler supported ones.

fix(routes/pdf): limit `outputEncoding` qs params to poppler charsets

---

src/plugins/tidy-css/index.js

`appendChild` returns the appended object, which we never do anything with

refactor(plugins/tidy-css): replace `appendChild` with `append`

---

README.md

Ownership of the hospital changes on 2023-04-01 to Somerset NHS Foundation Trust, so merge this change then.

docs(readme): update yeovil district hospital link

---

src/config/index.js

Issue resolved with optional chaining on the if statements.

fix(config): missing `CORS_ORIGIN` env variable throws error

---

Dockerfile

build(docker): remove htmltidy2 win32 and macos binaries

---

src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js

`.includes()` is way faster than `.test()`, see https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#string-searching

perf(plugins): replace `RegExp.test()` with `String.includes()`

---

src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/routes/pdf/html/schema.js
src/routes/pdf/txt/schema.js

BREAKING CHANGE: `outputEncoding` param removed from `pdf/html` and `pdf/txt` routes

refactor!: remove `outputEncoding` param for pdf routes

---

src/config/config.test.js
src/server.test.js

test(server): fully reset process.env to default after each test

---

.github/dependabot.yml
.vscode/settings.json
package-lock.json
package.json
src/plugins/docx-to-html/index.js
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-html/plugin.test.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-html/plugin.test.js

build(deps): replace `fix-utf8` with faster `fix-latin1-to-utf8`

---

README.md
src/routes/admin/healthcheck/index.js
src/routes/doc/txt/index.js
src/routes/docs/index.js
src/routes/docs/openapi/index.js
src/routes/docx/html/index.js
src/routes/docx/txt/index.js
src/routes/html/txt/index.js
src/routes/html/txt/route.test.js
src/routes/html/txt/route.test.js.snap
src/routes/html/txt/schema.js
src/routes/pdf/html/index.js
src/routes/pdf/txt/index.js
src/routes/rtf/html/index.js
src/routes/rtf/txt/index.js
test_resources/test_files/xhtml_valid.xhtml

feat(routes/html): add support for xhtml documents

---

Dockerfile

Fixes the following issue when attempting to deploy in certain instances:
This was due to the `node` user not having permissions to open `package.json`.

fix(docker): `node` user permissions

---

Dockerfile

build(dockerfile): use multi-stage build; reduce size by ~28%

---

.dockerignore
.env.template
.gitignore
.prettierignore
Dockerfile
README.md
src/app.js
src/config/config.test.js
src/config/index.js
src/plugins/pdf-to-html/plugin.test.js
src/plugins/pdf-to-txt/plugin.test.js
src/plugins/rtf-to-html/plugin.test.js

Makes leftover temp dirs from failed tests more apparent.

refactor: move temp dirs out of `dist/` and `src/`

---

Dockerfile

Stops the following error being thrown on shutdown:
```json
{
"level": "error",
"time": "2024-06-17T09:37:31.790Z",
"pid": 1,
"hostname": "ebd55f6520a2",
"err": {
"type": "Error",
"message": "EACCES: permission denied, rmdir '/usr/app/temp'",
"stack": "Error: EACCES: permission denied, rmdir '/usr/app/temp'",
"errno": -13,
"code": "EACCES",
"syscall": "rmdir",
"path": "/usr/app/temp"
},
"msg": "Error closing the application"
}
```

build(docker): change ownership of workdir

---

src/config/index.js
src/server.js

chore(config): define returned config obj types

---

.github/dependabot.yml
package-lock.json
package.json
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-html/plugin.test.js
src/plugins/pdf-to-txt/index.js
src/plugins/pdf-to-txt/plugin.test.js
src/routes/docx/html/index.js
src/routes/docx/html/route.test.js
src/routes/docx/html/schema.js
src/routes/html/txt/index.js
src/routes/html/txt/route.test.js
src/routes/html/txt/schema.js
src/routes/pdf/html/index.js
src/routes/pdf/html/route.test.js
src/routes/pdf/html/schema.js
src/routes/pdf/txt/index.js
src/routes/pdf/txt/route.test.js
src/routes/pdf/txt/schema.js
src/routes/rtf/html/index.js
src/routes/rtf/html/route.test.js
src/routes/rtf/html/schema.js
src/routes/rtf/txt/route.test.js
src/server.test.js

BREAKING CHANGE: all camelCase query string params renamed to snake_case, i.e. `backgroundColor` is now `background_color`

refactor(routes)!: rename camelCase query string params to snake_case

---

src/plugins/rtf-to-html/index.js

When data is written to a file, it may be temporarily stored in buffer memory to optimise performance. Because of this, there is a chance that Node will attempt to interact with a file before it has finished being written to disk, meaning that the RTF plugin may attempt to read partial files, posing a data integrity issue.
The `flush` param was added in Node 20.10, which ensures all data in the buffer is written to the disk immediately.

fix(plugins/rtf-to-html): flush file buffer to disk before reading file

---

package-lock.json
package.json
src/server.js
src/server.test.js

Stops pre-flight requests from getting caught.
OPTIONS routes don't need auth as they don't expose anything. They are rate-limited so protected against someone hammering them.

fix(server): disable auth for cors requests

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/link-check.yml
.github/workflows/optimise-images.yml

Most first party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes.

ci: use tags for immutable github actions
