Fdawgs/docsmith

package-lock.json
package.json
src/config/index.js
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-html/pdf-to-html.test.js
src/plugins/pdf-to-txt/index.js
src/plugins/pdf-to-txt/pdf-to-txt.test.js
src/routes/pdf/txt/index.js
src/routes/pdf/txt/schema.js

Add PDF-to-TXT Route

---

src/plugins/pdf-to-txt/index.js
src/plugins/pdf-to-txt/plugin.test.js
src/routes/pdf/txt/index.js
src/routes/pdf/txt/route.test.js

refactor(plugin/pdf-to-txt): read directly from buffer body

---

README.md
src/config/index.js
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-html/plugin.test.js
src/routes/rtf/html/index.js
src/routes/rtf/html/route.test.js
src/routes/rtf/html/schema.js
src/server.test.js

feat(routes/rtf/html): add rtf-to-html route

---

.dockerignore
.env.template
.github/workflows/ci.yml
Dockerfile
docker-compose.yml

build(docker): revamp file and deployment

---

src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-txt/index.js

fix(plugins): await `Object.assign()` and `fixUtf8()`

---

src/config/index.js
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-txt/index.js

Fix missing logs for majority of routes

---

.dockerignore
.gitignore
.prettierignore
README.md
ocr_lang_data/README.md
src/plugins/pdf-to-txt/index.js
src/utils/image-to-txt/index.js

fix(routes/pdf-to-txt)!: use local trained data; stop cache corruption

---

.env.template
src/server.js
src/server.test.js

fix(server): rate limit all 4xx and 5xx responses

---

src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-txt/index.js

fix(plugins): remove temp files for cancelled and timed out requests

---

package.json
src/config/config.test.js
src/config/index.js
src/routes/admin/healthcheck/index.js
src/routes/docs/index.js
src/routes/docs/json/index.js
src/routes/docx/html/index.js
src/routes/docx/txt/index.js
src/routes/pdf/html/index.js
src/routes/pdf/txt/index.js
src/routes/rtf/html/index.js
src/routes/rtf/txt/index.js
src/server.js
src/server.test.js

perf(server): reduce response header size

---

src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/rtf-to-txt/index.js

refactor(plugins): remove `fs.access()` calls

---

src/plugins/embed-html-images/index.js
src/plugins/embed-html-images/plugin.test.js
src/routes/pdf/html/index.js
src/routes/pdf/html/route.test.js
src/routes/rtf/html/index.js
src/routes/rtf/html/route.test.js

refactor(plugins/embed-html-images): convert to async function

---

README.md
package.json

BREAKING CHANGE: drop support for EOL node 15

chore!: drop support for node 15

---

src/config/index.js
src/routes/docs/openapi/schema.js

See https://ajv.js.org/guide/modifying-data.html#assigning-defaults

fix(config): `default` throws exceptions when used in `anyOf` schemas

---

package-lock.json
package.json
src/plugins/tidy-html/index.js

BREAKING CHANGE: HTML output now minified

perf(plugins/tidy-html)!: return minified html

---

src/routes/rtf/html/index.js

refactor(routes/rtf/html): remove embedding of html images

---

src/plugins/tidy-css/plugin.test.js

test(plugins/tidy-css): check `page-break-inside` is set

---

src/plugins/docx-to-html/index.js
src/plugins/docx-to-html/plugin.test.js
src/plugins/docx-to-txt/index.js
src/plugins/docx-to-txt/plugin.test.js

fix(plugins/docx): add header and footer to returned payloads

---

scripts/license-checker.js
src/app.js
src/config/index.js
src/server.js
src/utils/parse-string/index.js
test_resources/utils/genCombos.js

Same style as node docs for functions

chore: use nouns for leading word in function description tags

---

Dockerfile

build(docker): chown after `COPY` otherwise files will be owned by root

---

package-lock.json
package.json

build(deps-dev): bump esbuild from 0.20.1 to 0.20.2

---

src/utils/core-count/index.js

Alpine Linux does not have `lscpu` by default, so was throwing an error and not setting a cpu count.
This fix updates the util so it will fallback to using `cpus()` if an error occurs, or if it is an unsupported platform.

fix(utils/core-count): fallback to `cpus()` if platform not detected

---

src/routes/html/txt/index.js
src/routes/html/txt/route.test.js
src/routes/html/txt/route.test.js.snap
src/routes/html/txt/schema.js

feat(routes/html/txt): add `extractHidden` query string param

---

.github/workflows/cd.yml
Dockerfile
package-lock.json
package.json
src/app.js

build(deps-dev): replace nodemon with native watch

---

.env.template
src/config/index.js
src/utils/core-count/index.js
src/utils/core-count/util.test.js

refactor: revert to physical core count for cpu-bound processing

---

README.md
package-lock.json
package.json

build(deps-dev): bump the eslint group

---

package-lock.json
package.json
src/routes/docs/index.html
src/routes/docs/route.test.js.snap
src/server.test.js.snap
src/utils/core-count/index.js
test_resources/utils/bt-power-set.js

build(deps-dev): bump esbuild from 0.20.2 to 0.21.3

---

.github/workflows/cd.yml
package-lock.json
package.json
src/plugins/rtf-to-html/index.js
src/routes/admin/healthcheck/index.js
src/routes/doc/txt/index.js
src/routes/docs/openapi/index.js
src/routes/docx/html/index.js
src/routes/docx/txt/index.js
src/routes/html/txt/index.js
src/routes/pdf/html/index.js
src/routes/pdf/txt/index.js
src/routes/rtf/html/index.js
src/routes/rtf/txt/index.js

build(deps): bump node-unrtf from 5.0.1 to 5.0.2

---

.github/workflows/cd.yml
.npmrc
package-lock.json
package.json

chore(.npmrc): enforce strict engine checks

---

package-lock.json
package.json

build(deps): bump transistive dependencies

---

src/server.js
src/server.test.js

fix(server): cors support for 404 responses

---

.env.template
src/config/config.test.js

chore(.env.template): change `NODE_ENV` default to "production"

---

.eslintrc.js
package-lock.json
package.json
scripts/license-checker.js
src/config/config.test.js
src/config/index.js
src/plugins/docx-to-html/plugin.test.js
src/plugins/embed-html-images/index.js
src/plugins/embed-html-images/plugin.test.js
src/plugins/image-to-txt/index.js
src/plugins/pdf-to-html/index.js
src/plugins/pdf-to-txt/index.js
src/plugins/rtf-to-html/index.js
src/plugins/tidy-css/index.js
src/plugins/tidy-html/index.js
src/plugins/tidy-html/plugin.test.js
src/routes/docs/index.js
src/server.js

- [] Documentation has been updated and adheres to the style described in [CONTRIBUTING.md](https://github.com/fdawgs/.github/blob/main/CONTRIBUTING.md#documentation-style)

build(deps): remove upath

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/link-check.yml
.github/workflows/optimise-images.yml

ci: add top-level workflow permissions

---

src/routes/html/txt/route.test.js
src/routes/html/txt/route.test.js.snap

test(routes/html/txt): fix test name
